workspaceinfo:
  columns:
    - lastLoginTime
    - id
    - agreementAcceptedAt
    - email
    - name
    - ssoPrincipal
    - hadoopPrincipal
    - cpPrincipal
    - isAdmin
    - isDisabled
    - forcePasswordChange
    - deleted_at
    - state
    - lastStateChange
    - gid
    - exportStatusUpdatedAt
    - lastDeletedTenantAt
    - createdAt
    - updatedAt
    - peopleworkspaces
    #- maximalPrivileges #CSVとしては使わない
    #- maximalCapabilities #CSVとしては使わない
    #- authorizationRoles #CSVとしては使わない
